---
version: '3.8'

services:
  triggerdotdev:
    image: ghcr.io/triggerdotdev/trigger.dev:v3.0.0-beta.48
    container_name: triggerdotdev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3030:3030
  redis:
    image: redis
    ports:
      - 6379:6379
